# Generated by Django 5.0 on 2024-02-23 08:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='todo', unique=True),
            preserve_default=False,
        ),
    ]
